### ISSUE TITLE
how to see the reward cyc of deposit

### ISSUE THREAD

**Issue by ckfh** [cycloneprotocol/cyclone-contracts#8]

**Comment by ckfh** [comment]
The document shows that the profit will automatically be credited to the withdrawal wallet when withdraw,So it seems that can't directly view the reward,I don't know if my understanding is right

**Comment by ckfh** [comment]
> in the withdraw info, it only can see the deposit,exclude reward,so i want to know how to see the reward.. ps:im in bsc chain

solved

**Comment by bf945** [comment]
The reward is from CYC denomination. Say if you deposit certain amount of different assets, your CYC denomination will grow over time. That's your reward.
